# Crawling detik.com — Finance & Olahraga (Fast + Colab-style Output)

**Target:** 2 tema × 100 berita = 200 artikel  
**Sumber:** `finance.detik.com` & `sport.detik.com`  
**Output:** `detik_berita.csv` → kolom `id, isi_berita, tema` (A=id, B=isi, C=tema, sep=; Excel-friendly)  
**Teknik:** `requests + BeautifulSoup` untuk discovery link `/d-\d+/`, `trafilatura` untuk extract, `tqdm` + `ThreadPool`

## Requirements

Install di venv `PPWA` (sudah termasuk `tqdm` untuk progress bar Colab-style):

```bash
pip install trafilatura pandas requests beautifulsoup4 lxml tqdm ipykernel
python -m ipykernel install --user --name ppwa --display-name "Python (ppwa)"
```

| Library | Fungsi |
|---|---|
| `trafilatura` | `fetch_url` + `extract(include_comments=False)` — ekstraksi isi bersih |
| `requests` + `beautifulsoup4/lxml` | fetch indeks & discovery link `/d-\d+/` |
| `tqdm` | progress bar live kayak Google Colab |
| `pandas` | DataFrame, `value_counts`, preview & save CSV `utf-8-sig` |
| `ipykernel` | Jupyter kernel untuk VS Code/Jupyter |

**Wajib:** pilih kernel **Python (ppwa)** kanan atas VS Code sebelum Run.

In [57]:
# cek versi library
import trafilatura, pandas as pd
print(f"trafilatura {trafilatura.__version__} | pandas {pd.__version__}")
import requests, bs4, lxml
print(f"requests {requests.__version__} | bs4 {bs4.__version__} | lxml {lxml.__version__}")
import tqdm
print(f"tqdm {tqdm.__version__} OK")

trafilatura 2.2.0 | pandas 3.0.5
requests 2.34.2 | bs4 4.15.0 | lxml 6.1.3
tqdm 4.70.0 OK

In [58]:
import requests
from bs4 import BeautifulSoup
import trafilatura
import pandas as pd
import re, time
from tqdm.auto import tqdm  # progress bar Colab-style
from concurrent.futures import ThreadPoolExecutor, as_completed

print("imports OK - tqdm + ThreadPool ready", flush=True)

imports OK - tqdm + ThreadPool ready

## Konfigurasi 2 Tema

In [59]:
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept-Language": "id-ID,id;q=0.9,en;q=0.8",
}

TOPICS = [
    {"tema": "finance",  "url": "https://finance.detik.com/"},
    {"tema": "olahraga", "url": "https://sport.detik.com/"},
]

MAX_PER_TEMA = 100
OUTPUT_CSV = "detik_berita.csv"
pd.DataFrame(TOPICS)

       tema                         url
0   finance  https://finance.detik.com/
1  olahraga    https://sport.detik.com/

## Fungsi — Discovery link & Extract via trafilatura

In [60]:
def fetch(url):
    try:
        r = requests.get(url, headers=HEADERS, timeout=15)
        r.raise_for_status()
        return r.text
    except requests.RequestException as e:
        print(f"[ERROR] fetch {url}: {e}", flush=True)
        return None

def get_article_links(html, base_url):
    soup = BeautifulSoup(html, "lxml")
    seen, links = set(), []
    for a in soup.find_all("a", href=True):
        href = a["href"]
        if re.search(r"/d-\d+/", href) and href not in seen:
            if not href.startswith("http"):
                href = base_url.rstrip("/") + "/" + href.lstrip("/")
            if "detik.com" in href:
                seen.add(href)
                links.append(href)
    return links

def scrape_article_trafilatura(url):
    downloaded = trafilatura.fetch_url(url)
    if not downloaded:
        downloaded = fetch(url)
        if not downloaded:
            return None
    text = trafilatura.extract(downloaded, include_comments=False, include_tables=False)
    if not text or len(text.strip()) < 100:
        return None
    # FIX: pakai \s+ yang benar + hapus newline/; agar CSV Excel 1 baris = 1 artikel, 1 cell = 1 kolom
    text = re.sub(r"\s+", " ", text).strip()
    text = text.replace(";", ",").replace("\r", " ").replace("\n", " ")
    soup = BeautifulSoup(downloaded, "lxml")
    h1 = soup.find("h1")
    title = h1.get_text(strip=True) if h1 else url
    return {"judul": title, "url": url, "isi_berita": text}

### Test 1 URL (sanity check)

In [61]:
test_url = "https://finance.detik.com/moneter/d-8652973/muncul-isu-gaji-asn-dipindah-ke-bank-bumn-purbaya-buka-suara"
art = scrape_article_trafilatura(test_url)
if art:
    print(art["judul"][:80], flush=True)
    print(f"panjang isi: {len(art['isi_berita'])} char", flush=True)
    print(art["isi_berita"][:400] + "...", flush=True)
else:
    print("extract gagal", flush=True)

Muncul Isu Gaji ASN Dipindah ke Bank BUMN, Purbaya Buka Suara
panjang isi: 1881 char
Menteri Keuangan Purbaya Yudhi Sadewa buka suara merespons isu pemindahan payroll atau pembayaran gaji aparatur sipil negara (ASN) pemerintah daerah (Pemda) ke bank BUMN. Purbaya menegaskan tidak ada kebijakan dari pemerintah pusat terkait pemindahan tersebut. Isu pengalihan pembayaran gaji ASN dari Bank Pembangunan Daerah (BPD) ke bank BUMN sebelumnya muncul dalam Rapat Dengar Pendapat Umum (RDPU...

## Main — Crawling 100 berita per tema (FAST + Colab Output)

Target `100/100` per tema → total `200` artikel. `ThreadPoolExecutor(max_workers=5)` + `tqdm` + `OK` tetap. Crawl `/indeks?page=2..15` sampai 400 kandidat.

In [62]:
all_data = []
for topic in TOPICS:
    print(f"\n=== {topic['tema'].upper()} | {topic['url']} ===", flush=True)
    html = fetch(topic["url"])
    if not html:
        continue
    links = get_article_links(html, topic["url"])
    print(f"  Ditemukan {len(links)} link", flush=True)
    candidates = links[:MAX_PER_TEMA*4]
    # target 100 -> butuh ~400 kandidat, crawl indeks 2..15
    if len(candidates) < MAX_PER_TEMA*3:
        for page in range(2, 16):
            for extra_url in [topic["url"].rstrip("/") + f"/indeks?page={page}", topic["url"] + f"?page={page}"]:
                extra_html = fetch(extra_url)
                if extra_html:
                    extra_links = get_article_links(extra_html, topic["url"])
                    new = 0
                    for l in extra_links:
                        if l not in candidates:
                            candidates.append(l)
                            new += 1
                    if new > 0:
                        print(f"  + halaman {page} ({extra_url[-20:]}): +{new} -> total {len(candidates)}", flush=True)
                        break
            if len(candidates) >= MAX_PER_TEMA*4:
                break
        print(f"  Setelah indeks tambahan: {len(candidates)} kandidat", flush=True)
    
    scraped = []
    with ThreadPoolExecutor(max_workers=5) as ex:
        futures = {ex.submit(scrape_article_trafilatura, link): link for link in candidates}
        for f in tqdm(as_completed(futures), total=len(futures), desc=f"{topic['tema']}"):
            link = futures[f]
            try:
                art = f.result()
            except Exception as e:
                print(f"    ERROR {link[-40:]}: {e}", flush=True)
                continue
            if art:
                art["tema"] = topic["tema"]
                scraped.append(art)
                print(f"    OK | {art['judul'][:55]}... ({len(art['isi_berita'])} char)", flush=True)
                if len(scraped) >= MAX_PER_TEMA:
                    for fut in futures:
                        fut.cancel()
                    break
            else:
                print(f"    SKIP ...{link[-50:]}", flush=True)
    
    scraped = scraped[:MAX_PER_TEMA]
    print(f"  -> Terkumpul {len(scraped)}/{MAX_PER_TEMA} untuk {topic['tema']}", flush=True)
    all_data.extend(scraped)
    time.sleep(0.3)

# deduplicate by url
seen = set()
unique = []
for a in all_data:
    if a["url"] not in seen:
        seen.add(a["url"])
        unique.append(a)
all_data = unique
print(f"\nTotal unik: {len(all_data)} artikel", flush=True)

=== FINANCE | https://finance.detik.com/ ===
  Ditemukan 46 link
  + halaman 2 (ik.com/indeks?page=2): +3 -> total 49
  + halaman 3 (ik.com/indeks?page=3): +20 -> total 69
  + halaman 4 (ik.com/indeks?page=4): +20 -> total 89
  + halaman 5 (ik.com/indeks?page=5): +20 -> total 109
  + halaman 6 (ik.com/indeks?page=6): +17 -> total 126
  + halaman 7 (ik.com/indeks?page=7): +20 -> total 146
  + halaman 8 (ik.com/indeks?page=8): +19 -> total 165
  + halaman 9 (ik.com/indeks?page=9): +15 -> total 180
  + halaman 10 (k.com/indeks?page=10): +19 -> total 199
  + halaman 11 (k.com/indeks?page=11): +20 -> total 219
  + halaman 12 (k.com/indeks?page=12): +20 -> total 239
  + halaman 13 (k.com/indeks?page=13): +19 -> total 258
  + halaman 14 (k.com/indeks?page=14): +18 -> total 276
  + halaman 15 (k.com/indeks?page=15): +17 -> total 293
  Setelah indeks tambahan: 293 kandidat

finance:   0%|          | 0/293 [00:00<?, ?it/s]

    OK | Bandara Soetta-Husein Dibuka Lagi, Radin Inten Masih Di... (2221 char)

finance:   0%|          | 1/293 [00:00<02:01,  2.40it/s]

    OK | Bandara Soetta-Husein Siap Beroperasi Lagi Usai Dibuka... (2702 char)

finance:   1%|          | 2/293 [00:01<02:29,  1.94it/s]

    OK | Pramono Mau Terbitkan Obligasi, Purbaya: Kalau Uangnya ... (2446 char)

finance:   1%|          | 3/293 [00:01<01:34,  3.07it/s]

    OK | 7 Bandara Ditutup hingga 23.59 WIB, Ini Daftarnya... (2359 char)

finance:   1%|▏         | 4/293 [00:01<01:19,  3.63it/s]

    OK | Muncul Isu Gaji ASN Dipindah ke Bank BUMN, Purbaya Buka... (1881 char)
    OK | Terindikasi Isi BBM Berulang, 5.000 Nomor Polisi Kendar... (4423 char)
    OK | Penutupan Bandara Soetta Diperpanjang hingga 23.59 WIB... (1434 char)

finance:   2%|▏         | 7/293 [00:01<00:55,  5.17it/s]

    OK | Pinjaman Online Warga RI Makin Banyak, Tembus Rp 105 Tr... (1530 char)
    OK | 3 Bandara Masih Ditutup hingga Pukul 10.00 WIB, Ini Daf... (2810 char)

finance:   3%|▎         | 9/293 [00:01<00:42,  6.71it/s]

    OK | Alasan Buruh Minta Upah Naik 9% Tahun Depan... (3354 char)

finance:   3%|▎         | 10/293 [00:02<01:04,  4.41it/s]

    OK | Tok! DPR Setujui Pagu Anggaran Kemenkeu 2027 Rp 49,8 Tr... (2014 char)

finance:   4%|▍         | 11/293 [00:02<00:57,  4.88it/s]

    OK | Bos Danantara Jamin Kredit Bank BUMN ke Kopdes Merah Pu... (1812 char)
    OK | Prabowo Ingin Semua Warga RI Punya Rekening Bank, Kasih... (2494 char)

finance:   4%|▍         | 13/293 [00:02<00:44,  6.22it/s]

    OK | Aktivitas Jual Beli Pasar Agung Depok Tetap Ramai di Te... (847 char)
    OK | 5 Bandara Beroperasi 24 Jam Usai Erupsi Anak Krakatau... (759 char)

finance:   5%|▌         | 15/293 [00:03<00:46,  6.02it/s]

    OK | Kisah Pilot Helikopter Banting Setir Jadi Pebisnis Teh... (1139 char)
    OK | Mendulang Kasih dan Rupiah di Hari Raya Lewat Hampers... (1004 char)

finance:   6%|▌         | 17/293 [00:03<00:51,  5.31it/s]

    OK | Panen Cuan Layanan Sayang Anabul... (984 char)

finance:   6%|▌         | 18/293 [00:03<01:04,  4.29it/s]

    OK | Menangkis Serangan Hoaks Tarik Duit dari Bank... (949 char)
    OK | Bisnis Kura Kura Darat yang Bikin Dompet Gemuk... (6832 char)

finance:   7%|▋         | 20/293 [00:04<00:46,  5.86it/s]

    OK | Ide Bisnis Lilin Aromaterapi dari Rumah, Cetak Omzet Ra... (1164 char)

finance:   7%|▋         | 21/293 [00:04<00:46,  5.90it/s]

    OK | Rahasia Bisnis Batik Kekinian Beromzet Ratusan Juta Rup... (863 char)

finance:   8%|▊         | 22/293 [00:04<00:55,  4.84it/s]

    OK | Rahasia Bisnis Batik Kekinian Beromzet Ratusan Juta Rup... (526 char)

finance:   8%|▊         | 23/293 [00:04<00:49,  5.42it/s]

    OK | Warga Angke Terima Bantuan Beras 30 Kg, Jatah untuk Tig... (889 char)

finance:   8%|▊         | 24/293 [00:04<00:44,  6.00it/s]

    OK | Belatung Pendulang Cuan Puluhan Juta Rupiah... (821 char)

finance:   9%|▊         | 25/293 [00:05<00:49,  5.41it/s]

    OK | Purbaya Siap Bayar Utang Kereta Cepat, Uangnya Sudah Ad... (2311 char)
    OK | Purbaya Siap Gelontorkan Dana Bencana, Minta Hitungan J... (1025 char)

finance:   9%|▉         | 27/293 [00:05<00:48,  5.54it/s]

    OK | Bandara Ditutup Imbas Abu Vulkanik, KAI Tambah Perjalan... (1537 char)
    OK | 58 Dana Pensiun Telah Dibubarkan dalam 6 Tahun... (3011 char)

finance:  10%|▉         | 29/293 [00:05<00:44,  5.92it/s]

    OK | Utang Paylater Masyarakat RI Tembus Rp 31,56 Triliun Pa... (984 char)
    OK | Menhub Ungkap Alasan Penutupan 7 Bandara Diperpanjang... (3264 char)

finance:  11%|█         | 31/293 [00:05<00:42,  6.18it/s]

    OK | Pemerintah Sebut 2.961 Penerbangan Terdampak Erupsi Ana... (931 char)

finance:  11%|█         | 32/293 [00:06<00:45,  5.77it/s]

    OK | OJK Setop 951 Pinjol Ilegal... (1765 char)

finance:  11%|█▏        | 33/293 [00:06<01:01,  4.25it/s]

    OK | Bea Cukai Tindak 20.643 Kasus, Nilai Barang Rp 11,25 Tr... (1493 char)
    OK | Penerimaan Bea Cukai Rp 182,6 Triliun hingga Juli, 54,3... (1774 char)
    OK | Kemenkeu Usulkan Anggaran 2027 Rp49,8 Triliun... (1088 char)

finance:  12%|█▏        | 36/293 [00:06<00:40,  6.32it/s]

    OK | Menhub Jamin Maskapai Refund Tiket Pesawat 100% Imbas A... (1999 char)

finance:  13%|█▎        | 37/293 [00:07<00:44,  5.70it/s]

    OK | IHSG Ditutup Melemah ke Level 6.619... (670 char)

finance:  13%|█▎        | 38/293 [00:07<01:02,  4.09it/s]

    OK | Penetapan Lahan Pertanian 'Abadi' Capai 87,52%, Selesai... (3684 char)
    OK | Alasan Menhub Tak Mau Buru-buru Buka Bandara Soetta Mes... (1345 char)

finance:  14%|█▎        | 40/293 [00:07<00:45,  5.54it/s]

    OK | Buruh Minta Upah Minimum Tahun Depan Naik 7-9%... (3440 char)
    OK | Nilai Transaksi Aset Kripto RI Turun 28% Jadi Rp 20,52 ... (1615 char)

finance:  14%|█▍        | 42/293 [00:08<00:41,  6.00it/s]

    OK | Prabowo Mau Naikkan Anggaran Bencana, Purbaya Tunggu Hi... (1864 char)

finance:  15%|█▍        | 43/293 [00:08<00:43,  5.71it/s]

    OK | Purbaya Siapkan Rp 40 T Bayar Utang Kopdes ke Bank BUMN... (1359 char)

finance:  15%|█▌        | 44/293 [00:08<00:39,  6.24it/s]

    OK | Pertamina Batalkan Rencana Beli BBM Subsidi Tunjukkan S... (2204 char)
    OK | Angka Kemiskinan Berbeda dengan Versi Bank Dunia, BPS B... (3857 char)

finance:  16%|█▌        | 46/293 [00:08<00:37,  6.54it/s]

    OK | Purbaya Ajukan Anggaran Rp 49,8 Triliun Tahun Depan, bu... (4032 char)

finance:  16%|█▌        | 47/293 [00:08<00:37,  6.56it/s]

    OK | Mentan Pastikan Produksi Beras Aman saat El Nino, SPHP ... (4111 char)

finance:  16%|█▋        | 48/293 [00:08<00:37,  6.48it/s]

    OK | Warga RI Makin Banyak Utang Pinjol, Juli Tembus Rp 105 ... (1630 char)
    OK | Prabowo: Kebakaran Dekat IKN Harus Diperhatikan!... (2164 char)

finance:  17%|█▋        | 50/293 [00:09<00:31,  7.66it/s]

    OK | Modal Asing Serbu RI, Masuk Rp 1,9 Triliun di Agustus 2... (2104 char)
    OK | Pohon Sawit Muncul Usai Karhutla, Prabowo: Saya Minta N... (1200 char)

finance:  18%|█▊        | 52/293 [00:09<00:27,  8.84it/s]

    OK | Beras SPHP Ganti Nama Jadi 'Beras Kita', Mulai Dijual 2... (2574 char)

finance:  18%|█▊        | 53/293 [00:09<00:34,  6.90it/s]

    OK | 17 Perjalanan KRL Dibatalkan, Ini Alasannya... (1749 char)

finance:  18%|█▊        | 54/293 [00:09<00:40,  5.92it/s]

    OK | 38.375 Rekening Terindikasi Judi Online, OJK Bidik NIK ... (1640 char)
    OK | Prabowo Geram Ada Korporasi Biang Kerok Karhutla: Cabut... (1783 char)

finance:  19%|█▉        | 56/293 [00:10<00:40,  5.84it/s]

    OK | OJK Buka-bukaan Kondisi Keuangan RI di Tengah Perang Ir... (2416 char)
    OK | PT Timah Terjunkan Tim Pemadam Tangani Karhutla di Kalb... (3077 char)

finance:  20%|█▉        | 58/293 [00:10<00:37,  6.23it/s]

    OK | Purbaya soal K/L Minta Tambah Anggaran: Kalau Uangnya B... (2202 char)
    OK | Abu Vulkanik Anak Krakatau Picu Lonjakan Penjualan Mask... (682 char)

finance:  20%|██        | 60/293 [00:10<00:40,  5.75it/s]

    OK | 4 Penerbangan Garuda Dialihkan ke Kertajati Imbas Erups... (2371 char)

finance:  21%|██        | 61/293 [00:11<00:48,  4.80it/s]

    OK | Krakatau Meletus, Penerbangan Lumpuh, Bagaimana Mitigas... (3153 char)
    OK | Beras RI Kalah Murah dari Thailand-Vietnam, Mentan: Sub... (1559 char)
    OK | Prabowo: Alokasi Anggaran Mitigasi Bencana Harus Kita T... (1247 char)

finance:  22%|██▏       | 64/293 [00:11<00:40,  5.66it/s]

    OK | Beras Bulog Turun Mutu 380 Ribu Ton Bakal Dilelang Rp 1... (2387 char)
    OK | Telkom Siapkan Dividen hingga 90% dari Laba Bersih... (1271 char)

finance:  23%|██▎       | 66/293 [00:11<00:36,  6.21it/s]

    OK | Skema Tadpole Pindar Dinilai Rugikan Peminjam, Ini Alas... (5743 char)

finance:  23%|██▎       | 67/293 [00:12<00:47,  4.76it/s]

    OK | Toko Ke-1.400 MR.D.I.Y. Indonesia Resmi Dibuka, Ekspans... (3935 char)

finance:  23%|██▎       | 68/293 [00:12<00:45,  4.98it/s]

    OK | Telkom Diminta Konsolidasi Fiber BUMN, Aset Mana Saja y... (2463 char)
    OK | AirNaV: Abu Vulkanik Anak Krakatau ke Barat Daya, Diper... (2929 char)

finance:  24%|██▍       | 70/293 [00:12<00:41,  5.41it/s]

    OK | Purbaya Akui Ekonomi Terdampak Deretan Bencana Karhutla... (1256 char)
    OK | Pemerintah Tebar Bansos Beras 30 Kg Sekaligus buat Warg... (1384 char)

finance:  25%|██▍       | 72/293 [00:12<00:31,  6.93it/s]

    OK | Inalum Terjunkan Tim Tangani Karhutla di Mempawah... (3061 char)

finance:  25%|██▍       | 73/293 [00:13<00:33,  6.58it/s]

    OK | Pramono Tetap Mau Terbitkan Obligasi, Purbaya Bilang Be... (2500 char)

finance:  25%|██▌       | 74/293 [00:13<00:56,  3.84it/s]

    OK | Purbaya Masih Tunggu Ini buat Bayar Utang Kopdes... (1554 char)

finance:  26%|██▌       | 75/293 [00:13<00:52,  4.18it/s]

    OK | Bandara Soetta Tutup, Penerbangan Internasional Dialihk... (2526 char)
    OK | Hadapi Kemarau Kering, Pemerintah Tambah Alokasi Beras ... (3114 char)

finance:  26%|██▋       | 77/293 [00:14<00:35,  6.15it/s]

    OK | Cerita Purbaya Tak Sadar Rumahnya Kena Abu Vulkanik... (1375 char)
    OK | PLTP Gunung Salak Mulai Kembangkan Aset Karbon... (2980 char)

finance:  27%|██▋       | 79/293 [00:14<00:37,  5.78it/s]

    OK | Jalur Ketapang-Gilimanuk Diserbu Kendaraan, Antrean Sem... (3583 char)

finance:  27%|██▋       | 80/293 [00:14<00:36,  5.82it/s]

    OK | PGN Kenalkan Langsung Bentuk Pemanfaatan Gas Bumi Lewat... (4942 char)

finance:  28%|██▊       | 81/293 [00:14<00:40,  5.23it/s]

    OK | 7 Bandara Ditutup, 2.300 Penerbangan Terdampak... (2651 char)

finance:  28%|██▊       | 82/293 [00:15<00:37,  5.57it/s]

    OK | Sejumlah Gunung Api Erupsi, Konektivitas Transportasi H... (4414 char)

finance:  28%|██▊       | 83/293 [00:15<00:44,  4.74it/s]

    OK | Purbaya Siap Tambah Anggaran buat Penanganan Bencana Al... (1630 char)
    OK | Terdampak Abu Vulkanik, ASN Boleh Kerja dari Rumah?... (3239 char)

finance:  29%|██▉       | 85/293 [00:15<00:38,  5.40it/s]

    OK | Bandara Soetta Ditutup Imbas Abu Vulkanik, Kertajati Ja... (2807 char)
    OK | Zero ODOL 2027, Pemerintah Diminta Segera Rilis Roadmap... (3053 char)

finance:  30%|██▉       | 87/293 [00:15<00:29,  6.95it/s]

    OK | Laba Pegadaian Naik 84,6% Jadi Rp 6,59 Triliun di Semes... (4778 char)

finance:  30%|███       | 88/293 [00:16<00:35,  5.79it/s]

    OK | Bandara Soetta & Halim Ditutup hingga 18.00 WIB!... (1861 char)

finance:  30%|███       | 89/293 [00:16<00:35,  5.71it/s]

    OK | Harga Emas Antam Turun Lagi, Segini Harganya Sekarang... (1686 char)

finance:  31%|███       | 90/293 [00:16<00:41,  4.85it/s]

    OK | Dolar AS Pagi Ini Menguat ke Rp 17.664... (593 char)

finance:  31%|███       | 91/293 [00:16<00:40,  5.05it/s]

    OK | 467 Penerbangan Batal Imbas Abu Vulkanik, 150 Ribu Penu... (1772 char)
    OK | IHSG Dibuka 2 Arah, Berujung Melemah ke 6.627... (754 char)

finance:  32%|███▏      | 93/293 [00:16<00:27,  7.16it/s]

    OK | Laba Pupuk Indonesia Naik 253%, Harga Pupuk Turun, Apa ... (8525 char)

finance:  32%|███▏      | 94/293 [00:17<00:33,  5.89it/s]

    OK | Rekomendasi Saham Saat IHSG Melemah, Apa Saja?... (4788 char)
    OK | Cara Refund dan Reschedule Penerbangan yang Batal Imbas... (3036 char)

finance:  33%|███▎      | 96/293 [00:17<00:34,  5.70it/s]

    OK | Bandara Soetta-Lampung Masih Ditutup hingga Jam 9 Pagi... (1975 char)

finance:  33%|███▎      | 97/293 [00:17<00:36,  5.32it/s]

    OK | Debit Sungai Mahakam Menyusut, Muatan Tongkang Batu Bar... (785 char)

finance:  33%|███▎      | 98/293 [00:17<00:34,  5.72it/s]

    OK | Kemenkeu Sebut Pajak RI Rendah... (1638 char)

finance:  34%|███▍      | 99/293 [00:18<00:45,  4.30it/s]

    OK | Penyeberangan Merak-Bakauheni Tak Terdampak Erupsi Anak... (1931 char)

finance:  34%|███▍      | 99/293 [00:18<00:35,  5.42it/s]

  -> Terkumpul 100/100 untuk finance

=== OLAHRAGA | https://sport.detik.com/ ===
  Ditemukan 55 link
  + halaman 2 (ik.com/indeks?page=2): +15 -> total 70
  + halaman 3 (ik.com/indeks?page=3): +20 -> total 90
  + halaman 4 (ik.com/indeks?page=4): +18 -> total 108
  + halaman 5 (ik.com/indeks?page=5): +20 -> total 128
  + halaman 6 (ik.com/indeks?page=6): +19 -> total 147
  + halaman 7 (ik.com/indeks?page=7): +20 -> total 167
  + halaman 8 (ik.com/indeks?page=8): +20 -> total 187
  + halaman 9 (ik.com/indeks?page=9): +19 -> total 206
  + halaman 10 (k.com/indeks?page=10): +20 -> total 226
  + halaman 11 (k.com/indeks?page=11): +20 -> total 246
  + halaman 12 (k.com/indeks?page=12): +19 -> total 265
  + halaman 13 (k.com/indeks?page=13): +20 -> total 285
  + halaman 14 (k.com/indeks?page=14): +20 -> total 305
  + halaman 15 (k.com/indeks?page=15): +20 -> total 325
  Setelah indeks tambahan: 325 kandidat

olahraga:   0%|          | 0/325 [00:00<?, ?it/s]

    OK | Marc Marquez Makin Dekat, Jorge Martin Akan Lawan!... (2110 char)

olahraga:   0%|          | 1/325 [00:01<06:23,  1.18s/it]

    OK | Hasil China Masters 2026: Sabar/Reza Out, Wakil Indones... (2337 char)

olahraga:   1%|          | 2/325 [00:01<03:18,  1.63it/s]

    OK | Timnas Voli Putra dan Putri Indonesia Bidik 8 Besar Asi... (1952 char)

olahraga:   1%|          | 3/325 [00:01<02:05,  2.57it/s]

    OK | Pemanasan Timnas Basket 3x3 di Taiwan Jelang Asian Game... (2740 char)

olahraga:   1%|          | 4/325 [00:01<01:34,  3.39it/s]

    OK | Pol: Acosta Akan Menang Balapan dan Jadi Juara Dunia Cu... (1683 char)
    OK | MotoGP San Marino: Antusiasme Bezzecchi Balapan di 'Rum... (1832 char)

olahraga:   2%|▏         | 6/325 [00:01<00:55,  5.77it/s]

    OK | Dokter Perkirakan Kondisi Lengan Marc Marquez: Sekitar ... (1798 char)

olahraga:   2%|▏         | 7/325 [00:02<01:06,  4.81it/s]

    OK | KTM Suka Antusiasme Luca Marini... (2345 char)

olahraga:   2%|▏         | 8/325 [00:02<01:03,  4.96it/s]

    OK | Mourinho Tak Rasakan Tekanan buat Antar Madrid Juara Li... (1604 char)
    OK | Mbappe Bodo Amat PSG Sukses di Eropa Sejak Ditinggalnya... (1273 char)

olahraga:   3%|▎         | 10/325 [00:02<01:06,  4.72it/s]

    OK | Inter Milan dan 'Kutukan' 60 Tahun di Bernabeu... (1667 char)

olahraga:   3%|▎         | 11/325 [00:02<01:03,  4.97it/s]

    OK | Setelah 9 Tahun Gelar Basket, Kini LJK 2026 Rambah Pade... (3202 char)
    OK | Wasit Chris Kavanagh Disorot Usai Pimpin Laga Arsenal V... (1673 char)

olahraga:   4%|▍         | 13/325 [00:03<01:07,  4.64it/s]

    OK | Fiorentina Punya Pelatih Baru... (1223 char)

olahraga:   4%|▍         | 14/325 [00:03<00:58,  5.28it/s]

    OK | Ngedadak Padel: Ketika Padel Jadi Ajang Reuni... (3600 char)

olahraga:   5%|▍         | 15/325 [00:04<01:44,  2.98it/s]

    OK | Harry Kane: Menang Ballon d'Or 2026 atau Tidak Bukan Ke... (1392 char)

olahraga:   5%|▍         | 16/325 [00:04<01:29,  3.46it/s]

    OK | Menjaga Gaya Hidup Sehat Lewat Hyrox... (3802 char)

olahraga:   5%|▌         | 17/325 [00:04<01:13,  4.20it/s]

    OK | Harry Kane Takjub Bisa Lampaui Rekor Gol Ronaldo... (1386 char)

olahraga:   6%|▌         | 18/325 [00:04<01:13,  4.16it/s]

    OK | Kylian Mbappe Bidik Ballon d'Or 2026... (1606 char)
    OK | Men's World Tennis Championship: 3 Wakil RI Gagal ke Ba... (1918 char)

olahraga:   6%|▌         | 20/325 [00:05<01:09,  4.41it/s]

    OK | Anthony Gordon Sang 'Pelayan' Baru Barcelona... (1541 char)
    OK | Mo Salah Moncer, Bikin Rekor di Turki... (1186 char)
    OK | Usai Jadi Penyelamat Juventus, Gatti: Selalu Aku!... (1648 char)

olahraga:   7%|▋         | 23/325 [00:05<00:59,  5.06it/s]

    OK | Duka untuk Nepal, Seluruh Laga Liga Champions Diawali M... (1493 char)
    OK | Debut di Rok Cup Indonesia 2026, Barra Ghaisan Torehkan... (1595 char)

olahraga:   8%|▊         | 25/325 [00:05<00:52,  5.72it/s]

    OK | Sudahi Sedihmu, MU...... (1675 char)

olahraga:   8%|▊         | 26/325 [00:06<00:54,  5.50it/s]

    OK | Cerita Ndiaye Hampir Gabung Spurs Sebelum Dibajak Man C... (2186 char)

olahraga:   8%|▊         | 27/325 [00:06<00:50,  5.91it/s]

    OK | Jenderal Baru Barcelona itu Bernama Rodri... (1061 char)
    OK | Alonso Akui Salah Mainkan Caicedo Terlalu Cepat... (1139 char)

olahraga:   9%|▉         | 29/325 [00:06<00:39,  7.58it/s]

    OK | Barca Takkan Kekurangan Gol Meski Gagal Dapatkan Alvare... (1717 char)

olahraga:   9%|▉         | 30/325 [00:06<01:01,  4.81it/s]

    OK | Spalletti Enggan Permasalahkan Gol Pertama Milan... (1880 char)

olahraga:  10%|▉         | 31/325 [00:07<00:59,  4.94it/s]

    OK | AS Roma Bisa Saingi Inter?... (1820 char)
    OK | Datangkan Bek Jepang, Borneo Kini Punya 14 Pemain Asing... (2380 char)
    OK | Lille Vs Real Betis: Potensi Verdonk Vs Antony!... (1346 char)

olahraga:  10%|█         | 34/325 [00:07<00:44,  6.49it/s]

    OK | Problem Utama Chelsea Saat Ini Cuma...... (2135 char)

olahraga:  11%|█         | 35/325 [00:07<00:46,  6.22it/s]

    OK | Menanti Sejarah Indonesia di Liga Champions Lewat Calvi... (1376 char)

olahraga:  11%|█         | 36/325 [00:07<00:52,  5.48it/s]

    OK | Bandara Soetta Masih Tutup, Kepulangan Timnas U-20 Belu... (1428 char)

olahraga:  11%|█▏        | 37/325 [00:08<00:59,  4.85it/s]

    OK | MU Sudah Bagus, Kok... (1214 char)

olahraga:  12%|█▏        | 38/325 [00:08<00:53,  5.32it/s]

    OK | Belum Sepekan di Everton, Maitland-Niles Jebol Gawang M... (2979 char)
    OK | Arsenal Masih Sempurna, tapi Badai Akan Semakin Kencang... (2143 char)

olahraga:  12%|█▏        | 40/325 [00:08<00:44,  6.46it/s]

    OK | Rogers Ingatkan Para Lawan: Chelsea Bakal Makin Sip!... (1540 char)
    OK | 'Sulap' Ala Gabriel, Tendang Kepala Martinez dan Lolos ... (1838 char)

olahraga:  13%|█▎        | 42/325 [00:08<00:34,  8.23it/s]

    OK | Kalezic Keluhkan Rumput GBLA: Bagaimana Bisa Main di La... (1727 char)

olahraga:  13%|█▎        | 43/325 [00:08<00:43,  6.43it/s]

    OK | Pelatih-pelatih Super League Soroti Dihapusnya Official... (3880 char)

olahraga:  14%|█▎        | 44/325 [00:09<00:44,  6.32it/s]

    OK | Lolos Piala Asia U-20, Nova Arianto Ingin Timnas Indone... (1649 char)
    OK | Head to Head Real Madrid Vs Inter Milan di Liga Champio... (1682 char)
    OK | Betapa Cairnya Lini Depan Arsenal... (1954 char)

olahraga:  14%|█▍        | 47/325 [00:09<00:39,  6.95it/s]

    OK | Prediksi Juara Liga Champions 2026/27: Supercomputer Ja... (2434 char)

olahraga:  15%|█▍        | 48/325 [00:09<00:44,  6.23it/s]

    OK | Selembar Kertas Catatan Xabi Alonso ke Reece James, Apa... (1428 char)

olahraga:  15%|█▌        | 49/325 [00:10<00:54,  5.05it/s]

    OK | Anak Ronald Koeman Bikin Sejarah di Eredivisie: Main Ja... (3297 char)

olahraga:  15%|█▌        | 50/325 [00:10<00:55,  4.96it/s]

    OK | Jadwal Liga Champions Pekan Ini: Real Madrid Vs Inter, ... (2341 char)

olahraga:  16%|█▌        | 51/325 [00:10<00:49,  5.55it/s]

    OK | Chelsea Tak Kecewa-kecewa Banget... (1482 char)

olahraga:  16%|█▌        | 52/325 [00:10<00:46,  5.81it/s]

    OK | Fans Valencia Desak Presiden 'Balik ke Singapura' usai ... (1965 char)

olahraga:  16%|█▋        | 53/325 [00:10<00:42,  6.43it/s]

    OK | Serie A Baru 3 Pekan, Fiorentina Langsung Pecat Fabio G... (1351 char)

olahraga:  17%|█▋        | 54/325 [00:10<00:41,  6.61it/s]

    OK | Arteta: Tekel Konsa ke Morgan Rogers Itu Khas Inggris... (1388 char)

olahraga:  17%|█▋        | 55/325 [00:10<00:39,  6.86it/s]

    OK | Asian Games 2026: Timnas Basket Masuk Grup Neraka, CdM ... (2573 char)

olahraga:  17%|█▋        | 56/325 [00:11<00:52,  5.12it/s]

    OK | Derrick Michael Wujudkan Mimpi Masa Kecil Tampil di Asi... (2405 char)
    OK | Kalah di Perempatfinal AVC Beach Continental, Ini Kata ... (2005 char)

olahraga:  18%|█▊        | 58/325 [00:11<00:39,  6.74it/s]

    OK | Men's World Tennis Championship: Ganda Indonesia Tembus... (2197 char)

olahraga:  18%|█▊        | 59/325 [00:11<00:53,  4.94it/s]

    OK | Bali Bakal Gelar Turnamen Catur Internasional Akhir Okt... (2570 char)

olahraga:  18%|█▊        | 60/325 [00:11<00:52,  5.08it/s]

    OK | WEC 2026: Paruh Kedua Musim Dimulai, Team WRT 32 Lebih ... (1889 char)

olahraga:  19%|█▉        | 61/325 [00:12<00:46,  5.62it/s]

    OK | AVC Continental 2026: Bintang/Sofyan Hadapi Selandia Ba... (2294 char)

olahraga:  19%|█▉        | 62/325 [00:12<00:42,  6.22it/s]

    OK | Kyrchyn Gorge Jadi Panggung World Nomad Games... (2550 char)

olahraga:  19%|█▉        | 63/325 [00:12<00:39,  6.66it/s]

    OK | Belum Pernah Ikut Kelas Yoga? Yoga Outdoor Ini Cocok Un... (1708 char)

olahraga:  20%|█▉        | 64/325 [00:12<01:05,  3.98it/s]

    OK | Men's World Tennis Championship: Nathan Barki ke Peremp... (2070 char)

olahraga:  20%|██        | 65/325 [00:12<00:54,  4.77it/s]

    OK | Bakal Ada Jakarta Vertical Run 2026 Bulan November... (3194 char)
    OK | DKI Jakarta Gelar PON Pantai 2026 Bulan November... (2574 char)

olahraga:  21%|██        | 67/325 [00:13<01:02,  4.15it/s]

    OK | Gelar Juara MotoGP 2026 Jadi Ujian Ketahanan Marc Marqu... (2319 char)

olahraga:  21%|██        | 68/325 [00:13<00:55,  4.66it/s]

    OK | Hasil China Masters 2026: Sabar/Reza Menang, Melaju ke ... (1594 char)

olahraga:  21%|██        | 69/325 [00:13<00:49,  5.17it/s]

    OK | Kolaborasi dengan NPC, Kemenpora Genjot Pembinaan Atlet... (5554 char)

olahraga:  22%|██▏       | 70/325 [00:14<01:07,  3.80it/s]

    OK | Hasil China Masters 2026: Leo/Daniel Kena Comeback, Keo... (1549 char)
    OK | Jalan Panjang Bilal Hasan Menuju Titel UFC... (1369 char)

olahraga:  22%|██▏       | 72/325 [00:14<00:48,  5.21it/s]

    OK | Spesialnya Jakarta International 10K Tahun Ini... (4086 char)
    OK | Hasil China Masters 2026: Jojo Terhenti di Babak Kedua... (996 char)

olahraga:  23%|██▎       | 74/325 [00:14<00:46,  5.40it/s]

    OK | Agar MotoGP Indonesia 2026 Sukses di Dalam dan Luar Lin... (3304 char)

olahraga:  23%|██▎       | 75/325 [00:15<00:57,  4.32it/s]

    OK | Men's World Tennis Championship: Rafalentino dan Anthon... (1826 char)

olahraga:  23%|██▎       | 76/325 [00:15<00:57,  4.31it/s]

    OK | Francesco Bagnaia di Titik Terendah... (1489 char)

olahraga:  24%|██▎       | 77/325 [00:15<01:09,  3.59it/s]

    OK | Hasil China Masters 2026: Sabar/Reza Menang Dua Gim Lan... (1105 char)

olahraga:  24%|██▍       | 78/325 [00:15<01:02,  3.98it/s]

    OK | Atlet Bukan Satu-Satunya Kunci Kemajuan Olahraga Nasion... (1923 char)

olahraga:  24%|██▍       | 79/325 [00:16<00:59,  4.10it/s]

    OK | Ini Dia 20 Pebulutangkis Indonesia di Asian Games 2026... (2194 char)
    OK | Ketum KONI Pusat Sambut Positif Kejuaraan Pacu Kuda di ... (2641 char)

olahraga:  25%|██▍       | 81/325 [00:16<00:47,  5.09it/s]

    OK | Pordasi Akan Optimalkan Lapangan H.M. Hasan Gayo untuk ... (2491 char)

olahraga:  25%|██▌       | 82/325 [00:16<00:51,  4.72it/s]

    OK | Mangkuluhur Cup: Ketika Golf Bukan Lagi Sekadar Olahrag... (3082 char)

olahraga:  26%|██▌       | 83/325 [00:16<00:45,  5.32it/s]

    OK | 'Kampiun MotoGP 2026 Bukan yang Paling Banyak Menang, t... (1686 char)

olahraga:  26%|██▌       | 84/325 [00:17<00:48,  5.00it/s]

    OK | Men's World Tennis Championship: Nathan Barki Lolos ke ... (1908 char)

olahraga:  26%|██▌       | 85/325 [00:17<00:55,  4.30it/s]

    OK | MotoGP Aragon Selesai, Ini Nama Pemenang Bold Riders Po... (2466 char)
    OK | Marc Marquez Beri Pukulan untuk Rider-rider Aprilia!... (1347 char)

olahraga:  27%|██▋       | 87/325 [00:17<00:44,  5.29it/s]

    OK | China Masters 2026: Singkirkan Unggulan 1, Leo/Daniel k... (1825 char)

olahraga:  27%|██▋       | 88/325 [00:17<00:44,  5.34it/s]

    OK | Moto3: Veda Ega Sudah Empat Kali Gagal Raih Poin... (1497 char)

olahraga:  27%|██▋       | 89/325 [00:17<00:42,  5.61it/s]

    OK | MotoGP 2026: Aprilia Kian Termotivasi Kalahkan Marc Mar... (1618 char)

olahraga:  28%|██▊       | 90/325 [00:18<00:37,  6.35it/s]

    OK | Bukan Pukulan Hoki yang Runtuhkan Umar Nurmagomedov... (1886 char)

olahraga:  28%|██▊       | 91/325 [00:18<00:40,  5.78it/s]

    OK | Abdul Kadir Karding Jadi Ketum Perbasasi, Singgung Pemb... (3151 char)
    OK | Bagnaia Kena Mental? Bos Ducati: Ada Masalah Fokus... (1718 char)

olahraga:  29%|██▊       | 93/325 [00:18<00:30,  7.49it/s]

    OK | Bilal Hasan Bikin Legenda UFC Ini Kagum... (1471 char)

olahraga:  29%|██▉       | 94/325 [00:18<00:35,  6.52it/s]

    OK | Arwana Jaya dan Onic Sport Juara IPL Season 2... (3410 char)

olahraga:  29%|██▉       | 95/325 [00:18<00:42,  5.36it/s]

    OK | China Masters 2026: Jonatan Christie Kalahkan Leong Jun... (1203 char)

olahraga:  30%|██▉       | 96/325 [00:19<00:47,  4.81it/s]

    OK | Marc Marquez: Sirkuit Mandalika yang Terburuk Buatku... (1593 char)

olahraga:  30%|██▉       | 97/325 [00:19<00:44,  5.09it/s]

    OK | Men's World Tennis Championship: Gunawan Tembus Babak U... (1649 char)
    OK | Duel 300 Km/Jam Marc Marquez Vs Bezzecchi di Aragon: Mo... (1749 char)

olahraga:  30%|███       | 99/325 [00:20<00:55,  4.10it/s]

    OK | Jawa Timur Juara Kejurnas Panahan Tradisional 2026... (1709 char)

olahraga:  30%|███       | 99/325 [00:20<00:45,  4.93it/s]

  -> Terkumpul 100/100 untuk olahraga

Total unik: 200 artikel

## Result — CSV + Preview (3 kolom Excel-friendly: A=id, B=isi_berita, C=tema)

In [63]:
# Result CSV - 3 kolom Excel-friendly: id | isi_berita | tema (A=id, B=isi, C=tema)
import csv
# buat DataFrame dengan urutan sesuai request: A=id, B=isi_berita, C=tema
df = pd.DataFrame([{"id": idx, "isi_berita": a["isi_berita"].replace(";", ",").replace("\n"," ").replace("\r"," "), "tema": a["tema"]} for idx, a in enumerate(all_data, 1)])
df = df[["id", "isi_berita", "tema"]]  # urutan: A=id, B=isi_berita, C=tema
assert list(df.columns) == ["id", "isi_berita", "tema"], "Kolom harus 3: id, isi_berita, tema"
assert df.shape[1] == 3, "Jumlah kolom harus 3"
# cek isi tidak ada newline/; yang bikin Excel pindah cell/baris
assert not df["isi_berita"].str.contains(";").any(), "isi_berita masih ada ;"
# simpan dengan sep=; (Excel Indonesia) dan quote minimal agar 1 baris = 1 artikel
try:
    df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig", sep=";", quoting=csv.QUOTE_MINIMAL, lineterminator="\n")
    print(f"Saved -> {OUTPUT_CSV} : {df.shape[0]} rows x {df.shape[1]} cols (sep=';')", flush=True)
except PermissionError:
    alt = OUTPUT_CSV.replace(".csv", "_new.csv")
    df.to_csv(alt, index=False, encoding="utf-8-sig", sep=";", quoting=csv.QUOTE_MINIMAL, lineterminator="\n")
    print(f"[WARN] {OUTPUT_CSV} terkunci -> saved ke {alt} : {df.shape[0]} rows", flush=True)
print(f"Jumlah kolom: {df.shape[1]}", flush=True)
print(f"Daftar kolom (3 kolom): {df.columns.tolist()} -> A=id, B=isi_berita, C=tema", flush=True)
print(f"  - A:id         : nomor urut (1..n)", flush=True)
print(f"  - B:isi_berita : teks 1 baris (tanpa newline/;)", flush=True)
print(f"  - C:tema       : finance / olahraga", flush=True)
print(f"\nTotal artikel: {len(df)}", flush=True)
display(df.head(3))
print("\nDistribusi tema (tabel):", flush=True)
tabel_tema = df["tema"].value_counts().to_frame("jumlah")
tabel_tema = tabel_tema.reindex([t for t in ["finance", "olahraga"] if t in tabel_tema.index])
display(tabel_tema)
for tema, jumlah in tabel_tema["jumlah"].items():
    print(f"  - {tema}: {jumlah} artikel", flush=True)

Saved -> detik_berita.csv : 200 rows x 3 cols (sep=';')
Jumlah kolom: 3
Daftar kolom (3 kolom): ['id', 'isi_berita', 'tema'] -> A=id, B=isi_berita, C=tema
  - A:id         : nomor urut (1..n)
  - B:isi_berita : teks 1 baris (tanpa newline/;)
  - C:tema       : finance / olahraga

Total artikel: 200

   id                                         isi_berita     tema
0   1  Penutupan operasional Bandara Soekarno-Hatta b...  finance
1   2  InJourney Airports menjamin kesiapan operasion...  finance
2   3  Menteri Keuangan (Menkeu) Purbaya Yudhi Sadewa...  finance

Distribusi tema (tabel):

          jumlah
tema
finance      100
olahraga     100

  - finance: 100 artikel
  - olahraga: 100 artikel