## Import Library

In [8]:
import requests
import trafilatura
import pandas as pd
import re, time
from tqdm.auto import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed

print(f"trafilatura {trafilatura.__version__} | pandas {pd.__version__} | requests {requests.__version__} OK")

trafilatura 2.2.0 | pandas 3.0.5 | requests 2.34.2 OK

## Konfigurasi 2 Tema

In [9]:
HEADERS = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
    "Accept-Language": "id-ID,id;q=0.9,en;q=0.8",
}

TOPICS = [
    {"tema": "finance",  "url": "https://finance.detik.com/"},
    {"tema": "olahraga", "url": "https://sport.detik.com/"},
]

MAX_PER_TEMA = 100
OUTPUT_CSV = "detik_berita.csv"
pd.DataFrame(TOPICS)

       tema                         url
0   finance  https://finance.detik.com/
1  olahraga    https://sport.detik.com/

## Main — Crawling 100 berita per tema 

Target `100/100` per tema → total `200` artikel.

In [10]:
all_data = []
for topic in TOPICS:
    print(f"\n=== {topic['tema'].upper()} | {topic['url']} ===", flush=True)
    html = fetch(topic["url"])
    if not html:
        continue
    links = get_article_links(html, topic["url"])
    print(f"  Ditemukan {len(links)} link", flush=True)
    candidates = links[:MAX_PER_TEMA*4]
    # target 100 -> butuh ~400 kandidat, crawl indeks 2..15
    if len(candidates) < MAX_PER_TEMA*3:
        for page in range(2, 16):
            for extra_url in [topic["url"].rstrip("/") + f"/indeks?page={page}", topic["url"] + f"?page={page}"]:
                extra_html = fetch(extra_url)
                if extra_html:
                    extra_links = get_article_links(extra_html, topic["url"])
                    new = 0
                    for l in extra_links:
                        if l not in candidates:
                            candidates.append(l)
                            new += 1
                    if new > 0:
                        print(f"  + halaman {page} ({extra_url[-20:]}): +{new} -> total {len(candidates)}", flush=True)
                        break
            if len(candidates) >= MAX_PER_TEMA*4:
                break
        print(f"  Setelah indeks tambahan: {len(candidates)} kandidat", flush=True)
    
    scraped = []
    with ThreadPoolExecutor(max_workers=5) as ex:
        futures = {ex.submit(scrape_article_trafilatura, link): link for link in candidates}
        for f in tqdm(as_completed(futures), total=len(futures), desc=f"{topic['tema']}"):
            link = futures[f]
            try:
                art = f.result()
            except Exception as e:
                print(f"    ERROR {link[-40:]}: {e}", flush=True)
                continue
            if art:
                art["tema"] = topic["tema"]
                scraped.append(art)
                print(f"    OK | {art['url'][-60:]}... ({len(art['isi_berita'])} char)", flush=True)
                if len(scraped) >= MAX_PER_TEMA:
                    for fut in futures:
                        fut.cancel()
                    break
            else:
                print(f"    SKIP ...{link[-50:]}", flush=True)
    
    scraped = scraped[:MAX_PER_TEMA]
    print(f"  -> Terkumpul {len(scraped)}/{MAX_PER_TEMA} untuk {topic['tema']}", flush=True)
    all_data.extend(scraped)
    time.sleep(0.3)

# deduplicate by url
seen = set()
unique = []
for a in all_data:
    if a["url"] not in seen:
        seen.add(a["url"])
        unique.append(a)
all_data = unique
print(f"\nTotal unik: {len(all_data)} artikel", flush=True)

=== FINANCE | https://finance.detik.com/ ===
  Ditemukan 52 link
  + halaman 2 (ik.com/indeks?page=2): +3 -> total 55
  + halaman 3 (ik.com/indeks?page=3): +17 -> total 72
  + halaman 4 (ik.com/indeks?page=4): +18 -> total 90
  + halaman 5 (ik.com/indeks?page=5): +20 -> total 110
  + halaman 6 (ik.com/indeks?page=6): +19 -> total 129
  + halaman 7 (ik.com/indeks?page=7): +18 -> total 147
  + halaman 8 (ik.com/indeks?page=8): +17 -> total 164
  + halaman 9 (ik.com/indeks?page=9): +20 -> total 184
  + halaman 10 (k.com/indeks?page=10): +20 -> total 204
  + halaman 11 (k.com/indeks?page=11): +20 -> total 224
  + halaman 12 (k.com/indeks?page=12): +17 -> total 241
  + halaman 13 (k.com/indeks?page=13): +20 -> total 261
  + halaman 14 (k.com/indeks?page=14): +19 -> total 280
  + halaman 15 (k.com/indeks?page=15): +13 -> total 293
  Setelah indeks tambahan: 293 kandidat

finance:   0%|          | 0/293 [00:00<?, ?it/s]

    OK | berita-ekonomi-bisnis/d-8654941/harga-emas-antam-makin-jatuh... (1733 char)

finance:   0%|          | 1/293 [00:01<05:58,  1.23s/it]

    OK | pm-singapura-sumbangkan-kenaikan-gaji-rp-24-m-selama-5-tahun... (2183 char)
    OK | dibuatkan-rekening-saldo-awal-rp-50-ribu-sumber-apbn-rp-11-t... (1221 char)
    OK | /bri-ditugaskan-buka-rekening-warga-ri-khusus-aceh-lewat-bsi... (1274 char)

finance:   1%|▏         | 4/293 [00:01<01:50,  2.63it/s]

    OK | ru-mainan-dan-nostalgia-masa-kecil-di-kampoeng-mainan-blok-m... (1827 char)

finance:   2%|▏         | 5/293 [00:01<01:34,  3.06it/s]

    OK | 809/nasib-karyawan-telkom-yang-gedungnya-bakal-ditempati-bgn... (2796 char)

finance:   2%|▏         | 6/293 [00:02<01:43,  2.78it/s]

    OK | 654726/bps-ungkap-dtsen-bukan-daftar-penerima-bantuan-sosial... (4823 char)

finance:   2%|▏         | 7/293 [00:02<01:29,  3.21it/s]

    OK | it-apbn-dipakai-biayai-buka-rekening-bank-purbaya-buka-suara... (1401 char)
    OK | d-8654769/ratusan-penerbangan-di-inggris-delay-batal-ada-apa... (1850 char)
    OK | arga-ri-bakal-dapat-rekening-saldo-rp-50-ribu-bisa-dicairkan... (1730 char)

finance:   3%|▎         | 10/293 [00:02<00:47,  5.94it/s]

    OK | a-17-tahun-bakal-otomatis-dapat-rekening-tanpa-pergi-ke-bank... (1482 char)

finance:   4%|▍         | 11/293 [00:03<01:09,  4.05it/s]

    OK | -soal-bgn-pindah-ke-gedung-telkom-disewa-di-atas-harga-pasar... (3428 char)
    OK | -baru-usia-17-tahun-otomatis-dibuatkan-rekening-bri-atau-bsi... (1274 char)
    OK | 90719/kisah-pilot-helikopter-banting-setir-jadi-pebisnis-teh... (1139 char)

finance:   5%|▍         | 14/293 [00:03<01:04,  4.31it/s]

    OK | 61/adhi-karya-buka-suara-usai-diminta-tutup-semua-anak-usaha... (2675 char)
    OK | ta-ekonomi-bisnis/d-7320371/panen-cuan-layanan-sayang-anabul... (984 char)

finance:   5%|▌         | 16/293 [00:04<01:10,  3.91it/s]

    OK | erah-putih-pakai-duit-negara-purbaya-jamin-nggak-gagal-bayar... (2365 char)

finance:   6%|▌         | 17/293 [00:04<01:02,  4.38it/s]

    OK | snis/d-7319355/menangkis-serangan-hoaks-tarik-duit-dari-bank... (949 char)

finance:   6%|▌         | 18/293 [00:04<01:01,  4.45it/s]

    OK | ukm/d-7309999/bisnis-kura-kura-darat-yang-bikin-dompet-gemuk... (6832 char)

finance:   6%|▋         | 19/293 [00:05<00:55,  4.96it/s]

    OK | bisnis-lilin-aromaterapi-dari-rumah-cetak-omzet-ratusan-juta... (1164 char)

finance:   7%|▋         | 20/293 [00:05<00:50,  5.44it/s]

    OK | 3/rahasia-bisnis-batik-kekinian-beromzet-ratusan-juta-rupiah... (863 char)

finance:   7%|▋         | 21/293 [00:05<00:55,  4.87it/s]

    OK | 278891/mendulang-kasih-dan-rupiah-di-hari-raya-lewat-hampers... (1004 char)

finance:   8%|▊         | 22/293 [00:05<00:58,  4.61it/s]

    OK | awas-bursa-mineral-mau-ri-tentukan-harga-nikel-ini-alasannya... (3044 char)
    OK | janji-berikan-bonus-rp-3-m-buat-peraih-emas-asian-games-2026... (1298 char)

finance:   8%|▊         | 24/293 [00:05<00:40,  6.70it/s]

    OK | bisnis/d-7113302/belatung-pendulang-cuan-puluhan-juta-rupiah... (821 char)
    OK | v/d-7135571/rahasia-bisnis-batik-kekinian-omzet-ratusan-juta... (526 char)

finance:   9%|▉         | 26/293 [00:06<00:46,  5.72it/s]

    OK | 55579/purbaya-mau-kejar-potensi-pajak-perdagangan-emas-gelap... (1651 char)

finance:   9%|▉         | 27/293 [00:06<00:45,  5.81it/s]

    OK | /anak-krakatau-erupsi-harga-bahan-pokok-aman-ini-kata-mendag... (1814 char)

finance:  10%|▉         | 28/293 [00:06<00:44,  5.98it/s]

    OK | danantara-mau-beli-saham-bei-bursa-bakal-dimiliki-pemerintah... (2592 char)
    OK | ma-presentasi-online-umkm-ri-bisa-dapat-buyer-dari-33-negara... (2482 char)

finance:  10%|█         | 30/293 [00:06<00:50,  5.17it/s]

    OK | ntah-permudah-izin-tenaga-kerja-asing-5-hari-langsung-terbit... (2546 char)

finance:  11%|█         | 31/293 [00:07<00:46,  5.67it/s]

    OK | 501/purbaya-kebut-sistem-deteksi-pajak-ekspor-impor-pakai-ai... (1640 char)
    OK | unya-banyak-rencana-cek-penawaran-bri-multiguna-pre-approved... (5342 char)

finance:  11%|█▏        | 33/293 [00:07<00:46,  5.58it/s]

    OK | a-ekonomi-bisnis/d-8655321/bencana-jadi-beban-ekonomi-negara... (3520 char)
    OK | o-bisnis/d-8654607/bajaj-masih-eksis-di-tengah-gempuran-ojol... (1656 char)

finance:  12%|█▏        | 35/293 [00:07<00:38,  6.77it/s]

    OK | las/d-8655386/sah-sarjito-jadi-kepala-pengawas-bursa-mineral... (2408 char)

finance:  12%|█▏        | 36/293 [00:07<00:35,  7.24it/s]

    OK | k.com/energi/d-8655368/mglv-resmi-jadi-pemain-ai-data-center... (2254 char)
    OK | tikan-karhutla-di-tol-balsam-dan-bukit-tengkorak-sudah-padam... (2095 char)

finance:  13%|█▎        | 38/293 [00:08<00:34,  7.31it/s]

    OK | marga-jajaki-potensi-investasi-tol-baru-siapkan-dana-rp-12-t... (2357 char)

finance:  13%|█▎        | 39/293 [00:08<00:33,  7.57it/s]

    OK | ntech/d-8655330/bitcoin-masih-diminati-investor-ini-tandanya... (2526 char)

finance:  14%|█▎        | 40/293 [00:08<00:39,  6.44it/s]

    OK | 5/garuda-cek-pesawat-sebelum-terbang-lagi-imbas-abu-vulkanik... (4118 char)

finance:  14%|█▍        | 41/293 [00:08<01:03,  3.96it/s]

    OK | rofin-salurkan-bantuan-bagi-pengungsi-erupsi-gunung-sinabung... (3110 char)
    OK | ur/d-8655144/tol-probolinggo-banyuwangi-beroperasi-awal-2027... (2200 char)

finance:  15%|█▍        | 43/293 [00:09<00:43,  5.80it/s]

    OK | indak-10-juta-batang-rokok-ilegal-yang-rugikan-negara-rp-8-m... (2356 char)
    OK | -ilegal-di-jakarta-ditindak-bea-cukai-negara-rugi-rp-46-79-m... (2187 char)

finance:  15%|█▌        | 45/293 [00:09<00:36,  6.73it/s]

    OK | arang-susu-kental-manis-hingga-minuman-rasa-susu-di-menu-mbg... (1902 char)

finance:  16%|█▌        | 46/293 [00:09<00:41,  6.01it/s]

    OK | pkan-rp-40-t-bayar-utang-kopdes-ke-bank-bumn-jamin-tak-macet... (1359 char)

finance:  16%|█▌        | 47/293 [00:09<00:58,  4.17it/s]

    OK | 5085/emiten-rukun-raharja-rampungkan-akuisisi-5-saham-pt-lng... (2772 char)
    OK | ka-kemiskinan-berbeda-dengan-versi-bank-dunia-bps-buka-suara... (3857 char)

finance:  17%|█▋        | 49/293 [00:10<00:41,  5.82it/s]

    OK | tal-impor-produk-dari-permukiman-ilegal-israel-di-tepi-barat... (3399 char)

finance:  17%|█▋        | 50/293 [00:10<00:51,  4.75it/s]

    OK | 9/pertamina-batalkan-rencana-beli-bbm-subsidi-tunjukkan-stnk... (2204 char)

finance:  17%|█▋        | 51/293 [00:10<00:48,  5.00it/s]

    OK | /pengadaan-pemerintah-rp-1-200-t-bisa-jadi-peluang-buat-umkm... (5704 char)

finance:  18%|█▊        | 52/293 [00:11<01:07,  3.57it/s]

    OK | nen-begini-peran-pupuk-indonesia-dalam-jaga-ketahanan-pangan... (8169 char)
    OK | -bisnis/d-8655076/jaguar-land-rover-bakal-phk-4-000-karyawan... (2494 char)
    OK | kn-buka-suara-soal-karhutla-jarak-terdekat-dengan-kipp-30-km... (4401 char)

finance:  19%|█▉        | 55/293 [00:11<00:39,  6.03it/s]

    OK | dan-valas/d-8654836/rupiah-tekan-dolar-as-ke-level-rp-17-500... (932 char)

finance:  19%|█▉        | 56/293 [00:11<00:50,  4.71it/s]

    OK | 8654591/cabai-rawit-merah-makin-pedas-harga-tembus-rp91-ribu... (937 char)

finance:  19%|█▉        | 57/293 [00:12<01:13,  3.19it/s]

    OK | 655037/cuma-garuk-punggung-pria-ini-cuan-rp-220-juta-sebulan... (3173 char)

finance:  20%|█▉        | 58/293 [00:12<01:10,  3.31it/s]

    OK | 654774/rekomendasi-saham-yang-bisa-dilirik-saat-ihsg-menguat... (5335 char)

finance:  20%|██        | 59/293 [00:12<01:02,  3.77it/s]

    OK | 28/ihsg-dibuka-balik-ke-6-700-tak-lama-lengser-ke-zona-merah... (995 char)

finance:  20%|██        | 60/293 [00:13<01:00,  3.86it/s]

    OK | ntorkan-beras-premium-ke-ritel-modern-di-sejumlah-kota-besar... (2893 char)

finance:  21%|██        | 61/293 [00:13<01:08,  3.41it/s]

    OK | 4632/puan-minta-lahan-bekas-karhutla-jadi-kebun-sawit-diusut... (2484 char)

finance:  21%|██        | 62/293 [00:13<00:55,  4.18it/s]

    OK | bisnis/d-8654631/biang-kerok-sulitnya-kembalikan-aset-negara... (3739 char)
    OK | om/energi/d-8654629/pertashop-terancam-tutup-ini-penyebabnya... (2440 char)

finance:  22%|██▏       | 64/293 [00:13<00:40,  5.66it/s]

    OK | 54578/pemerintah-perkuat-database-penerima-gas-melon-lpg-3kg... (1131 char)

finance:  22%|██▏       | 65/293 [00:14<00:48,  4.66it/s]

    OK | -kerap-omong-gede-hingga-dicap-sombong-saat-awal-jadi-menkeu... (2124 char)
    OK | km-listrik-aliran-atas-krl-jabodetabek-dirawat-ini-prosesnya... (2815 char)

finance:  23%|██▎       | 67/293 [00:14<00:46,  4.87it/s]

    OK | ung-kelola-arus-kas-bisnis-jasamu-ikut-program-ini-solusinya... (1662 char)
    OK | m/energi/d-8654538/sampah-kini-disulap-jadi-bensin-dan-solar... (3688 char)

finance:  24%|██▎       | 69/293 [00:14<00:39,  5.62it/s]

    OK | -brevet-pajak-ab-saatnya-lanjut-brevet-c-untuk-cv-lebih-kuat... (1811 char)

finance:  24%|██▍       | 70/293 [00:15<00:44,  4.96it/s]

    OK | asional-butuh-staf-paham-pajak-lintas-negara-belajar-di-sini... (1883 char)

finance:  24%|██▍       | 71/293 [00:15<00:41,  5.41it/s]

    OK | bisnis/d-8654444/pemda-bisa-pinjam-ke-smi-bayarnya-pakai-dbh... (1414 char)

finance:  25%|██▍       | 72/293 [00:15<00:41,  5.30it/s]

    OK | ebut-bank-ri-siap-pungut-pajak-transaksi-digital-luar-negeri... (1429 char)

finance:  25%|██▍       | 73/293 [00:15<00:45,  4.88it/s]

    OK | /d-8654488/purbaya-terjunkan-anak-buah-awasi-ketat-dapur-mbg... (1703 char)

finance:  25%|██▌       | 74/293 [00:15<00:47,  4.60it/s]

    OK | mendasi-jasa-forwarder-import-barang-dari-china-ke-indonesia... (5704 char)
    OK | ya-rp-100-triliun-nganggur-purbaya-ingatkan-tak-perlu-minjam... (2422 char)
    OK | utih-akan-disewa-bgn-bos-telkom-hadirkan-peluang-bisnis-baru... (2594 char)

finance:  26%|██▋       | 77/293 [00:16<00:37,  5.82it/s]

    OK | truktur/d-8654625/4-fakta-utang-whoosh-dialihkan-ke-kemenkeu... (2620 char)
    OK | er-mahal-imbas-abu-anak-krakatau-pengawasan-mesti-diperketat... (2205 char)

finance:  27%|██▋       | 79/293 [00:16<00:34,  6.26it/s]

    OK | eter/d-8654356/penerima-bansos-bakal-dibuatkan-rekening-bank... (1971 char)

finance:  27%|██▋       | 80/293 [00:16<00:36,  5.89it/s]

    OK | aku-tak-pusingkan-anggaran-bgn-tahun-ini-tak-sampai-rp-200-t... (1889 char)

finance:  28%|██▊       | 81/293 [00:16<00:40,  5.23it/s]

    OK | a-waspada-solar-subsidi-bocor-selisih-harga-tembus-rp-18-200... (1682 char)

finance:  28%|██▊       | 82/293 [00:17<00:39,  5.38it/s]

    OK | ngkap-pemanfaatan-graha-merah-putih-oleh-bgn-masih-negosiasi... (1948 char)
    OK | ok-tokopedia-buka-suara-soal-kabar-blokir-tahan-saldo-seller... (3217 char)
    OK | om/bursa-dan-valas/d-8654139/ihsg-ditutup-menguat-1-ke-6-686... (978 char)

finance:  29%|██▉       | 85/293 [00:17<00:33,  6.18it/s]

    OK | ggak-pajak-jadi-landasan-perampasan-aset-purbaya-bilang-gini... (2184 char)
    OK | ngkap-1-juta-ton-nikel-tak-bertuan-di-sulteng-bakal-dilelang... (2160 char)

finance:  30%|██▉       | 87/293 [00:17<00:29,  7.07it/s]

    OK | rgi/d-8654088/bensin-campur-etanol-20-ditargetkan-jalan-2028... (2413 char)

finance:  30%|███       | 88/293 [00:18<00:35,  5.84it/s]

    OK | rbaya-buka-bukaan-utang-whoosh-cicilan-rp-1-t-tenor-80-tahun... (2477 char)

finance:  30%|███       | 89/293 [00:18<00:33,  6.13it/s]

    OK | dara-soetta-sempat-ditutup-barang-ekspor-impor-rp-3-t-mandek... (3266 char)
    OK | lim-kembali-beroperasi-mobilitas-penumpang-kembali-bergeliat... (1622 char)

finance:  31%|███       | 91/293 [00:18<00:33,  5.96it/s]

    OK | bank-perkuat-likuiditas-bikin-pertumbuhan-bisnis-tetap-sehat... (1885 char)

finance:  31%|███▏      | 92/293 [00:18<00:35,  5.73it/s]

    OK | 0-barang-rampasan-negara-nggak-laku-dilelang-ini-penyebabnya... (2559 char)
    OK | n-jepang-malaysia-eropa-penasaran-ada-potensi-hemat-rp-170-t... (3055 char)

finance:  32%|███▏      | 94/293 [00:18<00:26,  7.50it/s]

    OK | m-as-tiru-ri-pindahkan-sal-ke-bank-kita-pinteran-sedikit-lah... (2298 char)
    OK | 654017/emiten-ratu-dapat-restu-terbitkan-271-juta-saham-baru... (1822 char)

finance:  33%|███▎      | 96/293 [00:19<00:32,  6.13it/s]

    OK | ita-omong-gede-hingga-dicap-sombong-klaim-buat-kerek-ekonomi... (2222 char)

finance:  33%|███▎      | 97/293 [00:19<00:30,  6.50it/s]

    OK | /b50-sudah-menyebar-ke-6-050-spbu-tinggal-362-masih-transisi... (2009 char)
    OK | truk-sebut-aturan-zero-odol-belum-siap-di-2027-ini-alasannya... (2845 char)

finance:  34%|███▍      | 99/293 [00:19<00:28,  6.70it/s]

    OK | egara-kumpul-di-kek-kura-kura-bali-bahas-ai-hingga-investasi... (4594 char)

finance:  34%|███▍      | 99/293 [00:19<00:38,  4.99it/s]

  -> Terkumpul 100/100 untuk finance

=== OLAHRAGA | https://sport.detik.com/ ===
  Ditemukan 55 link
  + halaman 2 (ik.com/indeks?page=2): +17 -> total 72
  + halaman 3 (ik.com/indeks?page=3): +19 -> total 91
  + halaman 4 (ik.com/indeks?page=4): +20 -> total 111
  + halaman 5 (ik.com/indeks?page=5): +18 -> total 129
  + halaman 6 (ik.com/indeks?page=6): +20 -> total 149
  + halaman 7 (ik.com/indeks?page=7): +19 -> total 168
  + halaman 8 (ik.com/indeks?page=8): +20 -> total 188
  + halaman 9 (ik.com/indeks?page=9): +20 -> total 208
  + halaman 10 (k.com/indeks?page=10): +19 -> total 227
  + halaman 11 (k.com/indeks?page=11): +20 -> total 247
  + halaman 12 (k.com/indeks?page=12): +20 -> total 267
  + halaman 13 (k.com/indeks?page=13): +19 -> total 286
  + halaman 14 (k.com/indeks?page=14): +20 -> total 306
  + halaman 15 (k.com/indeks?page=15): +20 -> total 326
  Setelah indeks tambahan: 326 kandidat

olahraga:   0%|          | 0/326 [00:00<?, ?it/s]

    OK | -8653493/tekad-alwi-farhan-lampaui-batas-di-asian-games-2026... (1851 char)

olahraga:   0%|          | 1/326 [00:01<06:29,  1.20s/it]

    OK | asian-games-2026-putri-kw-pede-dengan-komposisi-beregu-putri... (2434 char)

olahraga:   1%|          | 2/326 [00:01<03:11,  1.69it/s]

    OK | ter-perkirakan-kondisi-lengan-marc-marquez-sekitar-50-persen... (1798 char)
    OK | michael-wujudkan-mimpi-masa-kecil-tampil-di-asian-games-2026... (2405 char)

olahraga:   1%|          | 4/326 [00:01<01:22,  3.91it/s]

    OK | -motogp-san-marino-2026-misi-marc-marquez-kejar-jorge-martin... (2033 char)
    OK | d-8655787/dari-hyrox-ke-10k-fanny-ghassani-pilih-pace-santai... (3377 char)

olahraga:   2%|▏         | 6/326 [00:01<01:02,  5.11it/s]

    OK | 8655272/xabi-alonso-redam-isu-estevao-mau-cabut-dari-chelsea... (1081 char)

olahraga:   2%|▏         | 7/326 [00:01<01:06,  4.81it/s]

    OK | om/sportstyle/d-8653072/menjaga-gaya-hidup-sehat-lewat-hyrox... (3802 char)

olahraga:   2%|▏         | 8/326 [00:02<00:58,  5.42it/s]

    OK | 655109/mourinho-real-madrid-vs-inter-milan-pertandingan-gila... (1605 char)

olahraga:   3%|▎         | 9/326 [00:02<00:59,  5.29it/s]

    OK | 26-sukses-padukan-trail-run-konser-musik-di-tangkuban-perahu... (3645 char)
    OK | ique-nggak-mau-ingat-ingat-psg-juara-bertahan-liga-champions... (1050 char)

olahraga:   3%|▎         | 11/326 [00:02<00:52,  5.94it/s]

    OK | pakbola/bola-dunia/d-8655780/presiden-fifa-vs-100-ribu-aduan... (1177 char)

olahraga:   4%|▎         | 12/326 [00:02<00:48,  6.42it/s]

    OK | esca-minta-pemain-city-kurang-kurangi-backpass-ke-donnarumma... (1606 char)

olahraga:   4%|▍         | 13/326 [00:02<00:46,  6.67it/s]

    OK | n-games-2026-prabowo-janjikan-bonus-rp-3-m-untuk-peraih-emas... (1373 char)
    OK | nia/d-8655334/raheem-sterling-tolak-tawaran-main-di-klub-ini... (933 char)

olahraga:   5%|▍         | 15/326 [00:03<00:41,  7.46it/s]

    OK | /uefa/d-8655327/arsenal-masih-100-pede-banget-tantang-napoli... (1443 char)

olahraga:   5%|▍         | 16/326 [00:03<00:42,  7.32it/s]

    OK | uniansyah-siap-debut-di-asian-games-2026-naik-kelas-ke-85-kg... (2655 char)

olahraga:   5%|▌         | 17/326 [00:03<00:45,  6.76it/s]

    OK | a-timnas-prancis-sebut-mbappe-tak-layak-raih-ballon-dor-2026... (1475 char)

olahraga:   6%|▌         | 18/326 [00:03<00:41,  7.36it/s]

    OK | persija-vs-persib-10-laga-terbaru-macan-kemayoran-kurang-oke... (1769 char)
    OK | kbola/uefa/d-8655261/mourinho-inter-milan-tim-terbaik-italia... (1492 char)

olahraga:   6%|▌         | 20/326 [00:03<00:30, 10.04it/s]

    OK | cuma-kurang-trofi-liga-champions-bertekad-juara-di-musim-ini... (1368 char)
    OK | apoli-vs-arsenal-calafiori-nantikan-gemuruh-stadion-maradona... (1400 char)

olahraga:   7%|▋         | 22/326 [00:04<00:45,  6.64it/s]

    OK | d-8655335/persija-vs-persib-perang-penggawa-timnas-indonesia... (1225 char)
    OK | 8655252/inter-milan-pulang-dari-bernabeu-dengan-kepala-tegak... (1405 char)
    OK | ourinho-selamatkan-vinicius-dari-cemooh-suporter-real-madrid... (1201 char)

olahraga:   8%|▊         | 25/326 [00:04<00:33,  9.06it/s]

    OK | la/uefa/d-8655195/arsenal-mau-buka-liga-champions-dengan-wow... (1292 char)
    OK | -8655208/mengapa-lionel-messi-masuk-nominasi-ballon-dor-2026... (1017 char)

olahraga:   8%|▊         | 27/326 [00:04<00:42,  7.07it/s]

    OK | s-2026-banjir-landa-nagoya-menpora-yakin-jepang-punya-plan-b... (2153 char)

olahraga:   9%|▊         | 28/326 [00:04<00:47,  6.31it/s]

    OK | 8655182/ngerinya-haaland-di-liga-champions-satu-gol-per-laga... (1110 char)

olahraga:   9%|▉         | 29/326 [00:05<00:46,  6.42it/s]

    OK | 193/inter-milan-membayar-mahal-blunder-blunder-lini-belakang... (1432 char)
    OK | liga-indonesia/d-8655279/fix-persija-menjamu-persib-di-sugbk... (1417 char)

olahraga:  10%|▉         | 31/326 [00:05<00:36,  8.10it/s]

    OK | -8655308/cdm-todotua-kami-monitoring-terus-kondisi-di-nagoya... (2066 char)

olahraga:  10%|▉         | 32/326 [00:05<00:37,  7.85it/s]

    OK | gal-ke-piala-asia-u-20-pemain-diaspora-indonesia-dibawa-bawa... (1901 char)
    OK | ort.detik.com/sepakbola/uefa/d-8655082/beda-nasib-dua-mbappe... (1209 char)
    OK | gris/d-8654259/michael-carrick-puas-dengan-performa-rashford... (1365 char)

olahraga:  11%|█         | 35/326 [00:05<00:40,  7.19it/s]

    OK | dan-menpora-mengukuhkan-tim-indonesia-untuk-asian-games-2026... (2832 char)

olahraga:  11%|█         | 36/326 [00:05<00:41,  6.94it/s]

    OK | kbola/uefa/d-8654252/napoli-vs-arsenal-il-partenopei-pincang... (1681 char)
    OK | martinez-hanya-bisa-ucapkan-terima-kasih-kepada-lionel-messi... (1252 char)

olahraga:  12%|█▏        | 38/326 [00:06<00:44,  6.47it/s]

    OK | ons-john-mcginn-cetak-gol-pembuka-musim-gabung-messi-ronaldo... (1716 char)
    OK | urtois-masuk-klub-100-liga-champions-kiper-ke-8-dalam-daftar... (2246 char)

olahraga:  12%|█▏        | 40/326 [00:06<00:34,  8.30it/s]

    OK | aaland-samai-aguero-jadi-top-skor-man-city-di-liga-champions... (1916 char)
    OK | 4332/milan-punya-gaya-main-yang-jelas-di-bawah-asuhan-amorim... (1655 char)

olahraga:  13%|█▎        | 42/326 [00:06<00:39,  7.12it/s]

    OK | iga-champions-malam-ini-arsenal-liverpool-dan-barcelona-main... (1566 char)

olahraga:  13%|█▎        | 43/326 [00:06<00:40,  7.04it/s]

    OK | 792/chivu-tak-marah-inter-bikin-salah-yang-penting-reaksinya... (1601 char)
    OK | nyol/d-8654771/messi-segera-akuisisi-klub-divisi-dua-spanyol... (1597 char)

olahraga:  14%|█▍        | 45/326 [00:07<00:32,  8.75it/s]

    OK | 8654748/lamine-yamal-tak-akan-memohon-agar-menang-ballon-dor... (1522 char)
    OK | arino-2026-jaga-puncak-klasemen-bukan-prioritas-jorge-martin... (1503 char)

olahraga:  14%|█▍        | 47/326 [00:07<00:46,  6.02it/s]

    OK | r-liga-champions-haaland-guirassy-dan-bartra-sama-sama-2-gol... (2203 char)

olahraga:  15%|█▍        | 48/326 [00:07<00:42,  6.50it/s]

    OK | artinez-doakan-alvarez-cepat-move-on-usai-gagal-ke-barcelona... (1925 char)

olahraga:  15%|█▌        | 49/326 [00:07<00:40,  6.82it/s]

    OK | 62/mac-allister-sedih-tak-ditawari-kontrak-baru-di-liverpool... (1591 char)
    OK | 8654746/porto-vs-man-city-panas-haaland-ribut-dengan-rosario... (1888 char)

olahraga:  16%|█▌        | 51/326 [00:07<00:34,  7.98it/s]

    OK | ortmund-dilarikan-ke-rs-usai-tumbang-saat-melawan-villarreal... (1989 char)

olahraga:  16%|█▌        | 52/326 [00:08<00:33,  8.29it/s]

    OK | s-como-berikan-jatah-tiket-liga-champions-ke-suporter-lansia... (1878 char)

olahraga:  16%|█▋        | 53/326 [00:08<00:37,  7.24it/s]

    OK | 8654685/klasemen-sementara-liga-champions-man-city-di-puncak... (1150 char)

olahraga:  17%|█▋        | 54/326 [00:08<00:53,  5.12it/s]

    OK | 3121/setelah-9-tahun-gelar-basket-kini-ljk-2026-rambah-padel... (3202 char)
    OK | style/d-8653076/ngedadak-padel-ketika-padel-jadi-ajang-reuni... (3600 char)

olahraga:  17%|█▋        | 56/326 [00:08<00:39,  6.88it/s]

    OK | ogp-san-marino-antusiasme-bezzecchi-balapan-di-rumah-sendiri... (1832 char)

olahraga:  17%|█▋        | 57/326 [00:09<00:57,  4.66it/s]

    OK | d-tennis-championship-3-wakil-ri-gagal-ke-babak-utama-seri-v... (1918 char)
    OK | ket/d-8654666/ganda-campuran-indonesia-kembali-rombak-pemain... (1442 char)

olahraga:  18%|█▊        | 59/326 [00:09<00:43,  6.14it/s]

    OK | ok-cup-indonesia-2026-barra-ghaisan-torehkan-catatan-positif... (1595 char)

olahraga:  18%|█▊        | 60/326 [00:09<00:39,  6.66it/s]

    OK | https://sport.detik.com/f1/d-8651642/mamma-mia-antonelli... (1491 char)
    OK | le/d-8651462/jete-run-festival-2026-selesai-masuk-rekor-muri... (3663 char)

olahraga:  19%|█▉        | 62/326 [00:10<01:07,  3.92it/s]

    OK | /menkomdigi-imbau-warga-waspadai-dampak-erupsi-anak-krakatau... (3597 char)
    OK | 603/mens-world-tennis-championship-karan-singh-juara-seri-iv... (1817 char)

olahraga:  20%|█▉        | 64/326 [00:10<00:49,  5.30it/s]

    OK | 74/wec-2026-sean-gelael-balapan-di-austin-dini-hari-start-p7... (1136 char)
    OK | 6/hasil-f1-gp-italia-2026-kimi-antonelli-menang-mercedes-1-2... (1837 char)

olahraga:  20%|██        | 66/326 [00:10<00:47,  5.48it/s]

    OK | .detik.com/moto-gp/d-8651046/ktm-suka-antusiasme-luca-marini... (2345 char)

olahraga:  21%|██        | 67/326 [00:11<00:50,  5.15it/s]

    OK | 8650342/wec-2026-wrt-32-meraba-cota-dari-hasil-free-practice... (2163 char)

olahraga:  21%|██        | 68/326 [00:11<00:47,  5.42it/s]

    OK | lih-ai-ogura-jadi-favorit-setelah-marc-marquez-ini-alasannya... (2311 char)

olahraga:  21%|██        | 69/326 [00:11<00:43,  5.96it/s]

    OK | le/d-8650215/minala-cup-padel-diikuti-lebih-dari-300-peserta... (2404 char)

olahraga:  21%|██▏       | 70/326 [00:11<00:48,  5.28it/s]

    OK | an-games-2026-timnas-basket-masuk-grup-neraka-cdm-optimistis... (2573 char)

olahraga:  22%|██▏       | 71/326 [00:11<00:47,  5.35it/s]

    OK | s-judoka-tuang-buah-pikiran-untuk-kemajuan-olahraga-nasional... (3447 char)
    OK | -perempatfinal-avc-beach-continental-ini-kata-bintang-sofyan... (2005 char)

olahraga:  22%|██▏       | 73/326 [00:11<00:35,  7.18it/s]

    OK | mens-world-tennis-championship-rafalentino-ethan-gagal-juara... (2488 char)
    OK | 99/wec-2026-paruh-kedua-musim-dimulai-team-wrt-32-lebih-pede... (1889 char)

olahraga:  23%|██▎       | 75/326 [00:12<00:38,  6.55it/s]

    OK | /mens-world-tennis-championship-ganda-indonesia-tembus-final... (2197 char)

olahraga:  23%|██▎       | 76/326 [00:12<00:36,  6.92it/s]

    OK | /bali-bakal-gelar-turnamen-catur-internasional-akhir-oktober... (2570 char)

olahraga:  24%|██▎       | 77/326 [00:12<00:55,  4.46it/s]

    OK | oli-putra-dan-putri-indonesia-bidik-8-besar-asian-games-2026... (1952 char)

olahraga:  24%|██▍       | 78/326 [00:13<01:02,  3.98it/s]

    OK | asil-china-masters-2026-sabar-reza-out-wakil-indonesia-habis... (2337 char)
    OK | port/d-8648227/kyrchyn-gorge-jadi-panggung-world-nomad-games... (2550 char)

olahraga:  25%|██▍       | 80/326 [00:13<00:45,  5.40it/s]

    OK | sta-akan-menang-balapan-dan-jadi-juara-dunia-cuma-soal-waktu... (1683 char)
    OK | inental-2026-bintang-sofyan-hadapi-selandia-baru-di-16-besar... (2294 char)

olahraga:  25%|██▌       | 82/326 [00:13<00:35,  6.97it/s]

    OK | emanasan-timnas-basket-3x3-di-taiwan-jelang-asian-games-2026... (2740 char)

olahraga:  25%|██▌       | 83/326 [00:13<00:44,  5.45it/s]

    OK | mens-world-tennis-championship-nathan-barki-ke-perempatfinal... (2070 char)
    OK | china-masters-2026-sabar-reza-menang-melaju-ke-perempatfinal... (1594 char)

olahraga:  26%|██▌       | 85/326 [00:14<00:48,  5.01it/s]

    OK | pernah-ikut-kelas-yoga-yoga-outdoor-ini-cocok-untuk-beginner... (1708 char)
    OK | d-8647394/bakal-ada-jakarta-vertical-run-2026-bulan-november... (3194 char)

olahraga:  27%|██▋       | 87/326 [00:14<00:35,  6.66it/s]

    OK | n/d-8647346/dki-jakarta-gelar-pon-pantai-2026-bulan-november... (2574 char)
    OK | p/d-8647200/marc-marquez-makin-dekat-jorge-martin-akan-lawan... (2110 char)

olahraga:  27%|██▋       | 89/326 [00:14<00:39,  6.00it/s]

    OK | 70/gelar-juara-motogp-2026-jadi-ujian-ketahanan-marc-marquez... (2319 char)
    OK | rasi-dengan-npc-kemenpora-genjot-pembinaan-atlet-disabilitas... (5554 char)

olahraga:  28%|██▊       | 91/326 [00:15<00:40,  5.81it/s]

    OK | rt-lain/d-8646269/jalan-panjang-bilal-hasan-menuju-titel-ufc... (1369 char)
    OK | 646249/hasil-china-masters-2026-jojo-terhenti-di-babak-kedua... (996 char)

olahraga:  29%|██▊       | 93/326 [00:15<00:41,  5.60it/s]

    OK | yle/d-8645952/spesialnya-jakarta-international-10k-tahun-ini... (4086 char)

olahraga:  29%|██▉       | 94/326 [00:15<00:38,  6.00it/s]

    OK | d-tennis-championship-rafalentino-dan-anthony-ke-babak-kedua... (1826 char)

olahraga:  29%|██▉       | 95/326 [00:15<00:38,  5.99it/s]

    OK | 20/atlet-bukan-satu-satunya-kunci-kemajuan-olahraga-nasional... (1923 char)

olahraga:  29%|██▉       | 96/326 [00:16<00:55,  4.18it/s]

    OK | agar-motogp-indonesia-2026-sukses-di-dalam-dan-luar-lintasan... (3304 char)
    OK | 7/motogp-2026-aprilia-kian-termotivasi-kalahkan-marc-marquez... (1618 char)
    OK | china-masters-2026-leo-daniel-kena-comeback-keok-di-16-besar... (1549 char)

olahraga:  30%|███       | 99/326 [00:16<00:32,  7.08it/s]

    OK | ik.com/moto-gp/d-8644946/francesco-bagnaia-di-titik-terendah... (1489 char)

olahraga:  30%|███       | 99/326 [00:16<00:38,  5.84it/s]

  -> Terkumpul 100/100 untuk olahraga

Total unik: 200 artikel

## Result — CSV + Preview

In [11]:
# Result CSV - 3 kolom Excel-friendly: id | isi_berita | tema (A=id, B=isi, C=tema)
import csv
# buat DataFrame dengan urutan sesuai request: A=id, B=isi_berita, C=tema
df = pd.DataFrame([{"id": idx, "isi_berita": a["isi_berita"].replace(";", ",").replace("\n"," ").replace("\r"," "), "tema": a["tema"]} for idx, a in enumerate(all_data, 1)])
df = df[["id", "isi_berita", "tema"]]  # urutan: A=id, B=isi_berita, C=tema
assert list(df.columns) == ["id", "isi_berita", "tema"], "Kolom harus 3: id, isi_berita, tema"
assert df.shape[1] == 3, "Jumlah kolom harus 3"
# cek isi tidak ada newline/; yang bikin Excel pindah cell/baris
assert not df["isi_berita"].str.contains(";").any(), "isi_berita masih ada ;"
# simpan dengan sep=; (Excel Indonesia) dan quote minimal agar 1 baris = 1 artikel
try:
    df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig", sep=";", quoting=csv.QUOTE_MINIMAL, lineterminator="\n")
    print(f"Saved -> {OUTPUT_CSV} : {df.shape[0]} rows x {df.shape[1]} cols (sep=';')", flush=True)
except PermissionError:
    alt = OUTPUT_CSV.replace(".csv", "_new.csv")
    df.to_csv(alt, index=False, encoding="utf-8-sig", sep=";", quoting=csv.QUOTE_MINIMAL, lineterminator="\n")
    print(f"[WARN] {OUTPUT_CSV} terkunci -> saved ke {alt} : {df.shape[0]} rows", flush=True)
print(f"Jumlah kolom: {df.shape[1]}", flush=True)
print(f"Daftar kolom:", flush=True)
print(f"  id         ", flush=True)
print(f"  isi_berita ", flush=True)
print(f"  tema       ", flush=True)
print(f"\nTotal artikel: {len(df)}", flush=True)
print("\nDistribusi tema (tabel):", flush=True)
tabel_tema = df["tema"].value_counts().to_frame("jumlah")
tabel_tema = tabel_tema.reindex([t for t in ["finance", "olahraga"] if t in tabel_tema.index])
display(tabel_tema)
for tema, jumlah in tabel_tema["jumlah"].items():
    print(f"  - {tema}: {jumlah} artikel", flush=True)

Saved -> detik_berita.csv : 200 rows x 3 cols (sep=';')
Jumlah kolom: 3
Daftar kolom:
  id
  isi_berita
  tema

Total artikel: 200

Distribusi tema (tabel):

          jumlah
tema
finance      100
olahraga     100

  - finance: 100 artikel
  - olahraga: 100 artikel